url: https://kt4records.github.io
#baseurl:

# Site settings
title: Kings Tone 4 Records
email: kt4records@gmail.com
description: "Independent record label based at Fres Wota 4, Efate, Vanuatu. Home to a range of upcoming Ni-Van artists"
markdown: kramdown
permalink: /:categories/:title
#fbcomments: yes
#media: http://localhost:4000
media: https://drive.google.com/uc?id=
adbitly: https://adbitly.com/st/?api=2c7fc6867b37ffc6cc0b7308d00b2369b3f60ef1&url=
