url: https://kt4records.github.io
#baseurl:

# Site settings
title: Kings Tone 4 Records
email: kt4records@gmail.com
description: "Independent record label based at Fres Wota 4, Efate, Vanuatu. Home to a range of upcoming Ni-Van artists"
markdown: kramdown
permalink: /:categories/:title
fbcomments: yes
#media: http://localhost:4000
media: https://kt4records.updog.co
adbitly: http://gg-l.xyz/
